import assert from 'node:assert/strict';
import { existsSync, mkdirSync, mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { test } from 'node:test';
import {
  describePackageManager,
  describePackageManagerDetails,
  detectPackageManager,
  packageManagerVersion,
} from '../src/package-manager';
import { makeFixture, makePnpmProject, makeTree } from './helpers';

const project = (extra: object = {}, files: Record<string, object> = {}) =>
  makeTree({ 'package.json': { name: 'app', version: '1.0.0', ...extra }, ...files });
const textFile = (root: string, rel: string, text: string) => {
  const file = join(root, rel);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, text);
};

test('npm: the lockfile format is a hint, never an invented version', () => {
  for (const [v, hint] of [
    ['3', '7 or newer'],
    ['2', '7 or 8'],
    ['1', '5 or 6'],
  ] as const) {
    const pm = detectPackageManager(
      project({}, { 'package-lock.json': { lockfileVersion: Number(v) } }),
    );
    assert.deepEqual(
      [pm.name, pm.version, pm.versionHint, pm.lockfile, pm.lockfileVersion, pm.layout],
      ['npm', undefined, hint, 'package-lock.json', v, 'node_modules'],
    );
  }
  const shrink = detectPackageManager(
    project({}, { 'npm-shrinkwrap.json': { lockfileVersion: 3 } }),
  );
  assert.equal(shrink.lockfile, 'npm-shrinkwrap.json');
  assert.equal(describePackageManager(detectPackageManager(makeFixture())), 'npm 7 or newer');
});

test('npm: an exact version only when the project declares it (Corepack packageManager field)', () => {
  const pm = detectPackageManager(
    project({ packageManager: 'npm@10.9.4' }, { 'package-lock.json': { lockfileVersion: 3 } }),
  );
  assert.deepEqual(
    [pm.name, pm.version, pm.versionHint, pm.source],
    ['npm', '10.9.4', undefined, 'package.json packageManager'],
  );
});

test('Yarn classic: the v1 lockfile; an exact version from .yarnrc yarn-path', () => {
  const root = project();
  textFile(root, 'yarn.lock', '# THIS IS AN AUTOGENERATED FILE.\n# yarn lockfile v1\n\n');
  const pm = detectPackageManager(root);
  assert.deepEqual(
    [pm.name, pm.family, pm.version, pm.versionHint, pm.lockfileVersion],
    ['yarn', 'classic', undefined, '1.x', '1'],
  );
  assert.equal(describePackageManager(pm), 'Yarn 1.x (classic)');
  textFile(root, '.yarnrc', 'yarn-path ".yarn/releases/yarn-1.22.19.cjs"\n');
  const exact = detectPackageManager(root);
  assert.deepEqual(
    [exact.version, exact.versionHint, exact.source],
    ['1.22.19', undefined, 'yarnPath in the Yarn config'],
  );
});

test('Yarn Berry: the lockfile format gives the major version as a hint; yarnPath or packageManager give the exact one', () => {
  for (const [lock, hint] of [
    ['8', '4.x'],
    ['6', '3.x'],
    ['5', '2.x'],
  ] as const) {
    const root = project();
    textFile(root, 'yarn.lock', `__metadata:\n  version: ${lock}\n  cacheKey: 10c0\n`);
    const pm = detectPackageManager(root);
    assert.deepEqual(
      [pm.name, pm.family, pm.versionHint, pm.lockfileVersion],
      ['yarn', 'berry', hint, lock],
    );
  }
  const viaPath = project();
  textFile(viaPath, 'yarn.lock', '__metadata:\n  version: 8\n');
  textFile(
    viaPath,
    '.yarnrc.yml',
    'yarnPath: .yarn/releases/yarn-4.5.3.cjs\nnodeLinker: node-modules\n',
  );
  assert.equal(detectPackageManager(viaPath).version, '4.5.3');
  const viaField = project({ packageManager: 'yarn@4.5.3+sha224.0123abcd' });
  textFile(viaField, 'yarn.lock', '__metadata:\n  version: 8\n');
  const pm = detectPackageManager(viaField);
  assert.deepEqual([pm.version, pm.source], ['4.5.3', 'package.json packageManager']);
  assert.equal(describePackageManager(pm), 'Yarn 4.5.3 (Berry)');
});

test("Yarn Plug'n'Play is recognised by .pnp.cjs, .pnp.js or .pnp.data.json, even without a lockfile", () => {
  for (const marker of ['.pnp.cjs', '.pnp.js', '.pnp.data.json']) {
    const root = project();
    textFile(root, marker, '');
    const pm = detectPackageManager(root);
    assert.deepEqual([pm.name, pm.family, pm.layout], ['yarn', 'berry', 'pnp'], marker);
  }
});

test('pnpm: the exact version is recorded by pnpm itself; otherwise only a lockfile hint', () => {
  const installed = makePnpmProject({ prod: ['a'], packages: [{ name: 'a' }] });
  const pm = detectPackageManager(installed);
  assert.deepEqual(
    [pm.name, pm.version, pm.versionHint, pm.source, pm.lockfile, pm.lockfileVersion, pm.layout],
    [
      'pnpm',
      '9.15.9',
      undefined,
      'node_modules/.modules.yaml',
      'pnpm-lock.yaml',
      '9.0',
      'pnpm-store',
    ],
  );
  assert.equal(describePackageManager(pm), 'pnpm 9.15.9');
  for (const [lock, hint] of [
    ['9.0', '9.x'],
    ['6.0', '8.x'],
    ['5.4', '7.x'],
  ] as const) {
    const root = project();
    textFile(root, 'pnpm-lock.yaml', `lockfileVersion: '${lock}'\n`);
    const only = detectPackageManager(root);
    assert.deepEqual([only.name, only.version, only.versionHint], ['pnpm', undefined, hint]);
  }
});

test('pnpm: what the install recorded wins over what package.json declares', () => {
  const root = project({ packageManager: 'pnpm@8.0.0' });
  textFile(root, 'node_modules/.modules.yaml', 'packageManager: pnpm@9.15.9\n');
  textFile(root, 'pnpm-lock.yaml', "lockfileVersion: '9.0'\n");
  assert.equal(detectPackageManager(root).version, '9.15.9');
});

test("pnpm's hoisted linker is told apart from the default layout", () => {
  const root = project();
  textFile(root, 'node_modules/a/package.json', '{"name":"a","version":"1.0.0"}'); // a real folder
  textFile(root, 'node_modules/.pnpm/x@1.0.0/node_modules/x/package.json', '{}'); // the store also exists
  textFile(root, 'pnpm-lock.yaml', "lockfileVersion: '9.0'\n");
  assert.equal(detectPackageManager(root).layout, 'node_modules');
});

test('evidence on disk wins over the declared name; a declaration alone is used when there is no evidence', () => {
  const lying = project(
    { packageManager: 'pnpm@9.0.0' },
    { 'package-lock.json': { lockfileVersion: 3 } },
  );
  assert.equal(detectPackageManager(lying).name, 'npm');
  const declaredOnly = detectPackageManager(project({ packageManager: 'pnpm@9.1.0' }));
  assert.deepEqual(
    [declaredOnly.name, declaredOnly.version, declaredOnly.source],
    ['pnpm', '9.1.0', 'package.json packageManager'],
  );
  const nothing = detectPackageManager(project());
  assert.deepEqual(
    [nothing.name, nothing.version, nothing.source],
    ['unknown', undefined, 'no lockfile found'],
  );
  assert.equal(describePackageManager(nothing), 'unknown');
  assert.equal(detectPackageManager(project({ packageManager: 'bun@1.1.0' })).name, 'unknown'); // only npm, Yarn and pnpm are named
});

test('a package manager is never executed: a hostile yarnPath script does not run', () => {
  const root = project();
  const marker = join(mkdtempSync(join(tmpdir(), 'nlt-marker-')), 'EXECUTED');
  textFile(root, 'yarn.lock', '__metadata:\n  version: 8\n');
  textFile(
    root,
    '.yarn/releases/yarn-4.9.9.cjs',
    `require('fs').writeFileSync(${JSON.stringify(marker)}, 'x');`,
  );
  textFile(root, '.yarnrc.yml', 'yarnPath: .yarn/releases/yarn-4.9.9.cjs\n');
  const pm = detectPackageManager(root);
  assert.equal(pm.version, '4.9.9'); // read from the file NAME
  assert.equal(existsSync(marker), false, 'the project-supplied script must not be run');
});

test('version and detail helpers', () => {
  const pm = detectPackageManager(makePnpmProject({ prod: ['a'], packages: [{ name: 'a' }] }));
  assert.equal(packageManagerVersion(pm), '9.15.9');
  assert.equal(
    describePackageManagerDetails(pm),
    'lockfile pnpm-lock.yaml v9.0, pnpm virtual store layout',
  );
  assert.equal(packageManagerVersion({ name: 'unknown', source: '', layout: 'node_modules' }), '');
});

test('a corrupt lockfile only costs the version hint, never the run', () => {
  for (const content of ['', '{ broken', '[]', 'null', '12']) {
    const root = project();
    textFile(root, 'package-lock.json', content);
    const pm = detectPackageManager(root);
    assert.deepEqual(
      [pm.name, pm.lockfile, pm.versionHint],
      ['npm', 'package-lock.json', undefined],
      JSON.stringify(content),
    );
  }
});
