#!/usr/bin/env node
/* eslint-disable */
// @ts-nocheck
'use strict';

const RAW_RUNTIME_STATE =
  '{\
  "__info": [\
    "This file is automatically generated. Do not touch it, or risk",\
    "your modifications being lost."\
  ],\
  "dependencyTreeRoots": [\
    {\
      "name": "tiny",\
      "reference": "workspace:."\
    }\
  ],\
  "enableTopLevelFallback": true,\
  "ignorePatternData": "(^(?:\\\\.yarn\\\\/sdks(?:\\\\/(?!\\\\.{1,2}(?:\\\\/|$))(?:(?:(?!(?:^|\\\\/)\\\\.{1,2}(?:\\\\/|$)).)*?)|$))$)",\
  "fallbackExclusionList": [\
    ["tiny", ["workspace:."]]\
  ],\
  "fallbackPool": [\
  ],\
  "packageRegistryData": [\
    [null, [\
      [null, {\
        "packageLocation": "./",\
        "packageDependencies": [\
          ["ms", "npm:2.1.3"]\
        ],\
        "linkType": "SOFT"\
      }]\
    ]],\
    ["ms", [\
      ["npm:2.1.3", {\
        "packageLocation": "../../../../../../../Users/dev/.yarn/berry/cache/ms-npm-2.1.3-81ff3cfac1-10c0.zip/node_modules/ms/",\
        "packageDependencies": [\
          ["ms", "npm:2.1.3"]\
        ],\
        "linkType": "HARD"\
      }]\
    ]],\
    ["tiny", [\
      ["workspace:.", {\
        "packageLocation": "./",\
        "packageDependencies": [\
          ["tiny", "workspace:."],\
          ["ms", "npm:2.1.3"]\
        ],\
        "linkType": "SOFT"\
      }]\
    ]]\
  ]\
}';

function $$SETUP_STATE(hydrateRuntimeState, basePath) {
  // (Yarn's runtime omitted: the tests only read the state above, which is unmodified Yarn 4.5.3 output)
}
